{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMw2IhvVltPdVPfO1iD7CUV",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bernardovigill/college_activities/blob/main/AtividadeAula7POO.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "Cbkjbqhmw6s4",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 596
        },
        "outputId": "97ad4f1a-3935-4db3-b1d8-b57484117ae3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "1 – Cadastrar funcionário\n",
            "2 – Cadastrar gerente\n",
            "3 – Cadastrar vendedor\n",
            "4 – Bonificar funcionário\n",
            "5 – Bonificar gerente\n",
            "6 – Autenticar senha gerente\n",
            "7 – Atualizar quantidade de vendas do vendedor\n",
            "8 – Calcular salário do vendedor\n",
            "9 - Listar funcionários\n",
            "10 - Listar gerentes\n",
            "11 - Listar vendedores\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "KeyboardInterrupt",
          "evalue": "Interrupted by user",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_5619/3124948458.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     60\u001b[0m   \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     61\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 62\u001b[0;31m       \u001b[0mop\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'\\nSelecione uma opção válida: '\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     63\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mop\u001b[0m \u001b[0;34m>=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mop\u001b[0m \u001b[0;34m<=\u001b[0m \u001b[0;36m11\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     64\u001b[0m         \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py\u001b[0m in \u001b[0;36mraw_input\u001b[0;34m(self, prompt)\u001b[0m\n\u001b[1;32m   1175\u001b[0m                 \u001b[0;34m\"raw_input was called, but this frontend does not support input requests.\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1176\u001b[0m             )\n\u001b[0;32m-> 1177\u001b[0;31m         return self._input_request(\n\u001b[0m\u001b[1;32m   1178\u001b[0m             \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprompt\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1179\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_parent_ident\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"shell\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py\u001b[0m in \u001b[0;36m_input_request\u001b[0;34m(self, prompt, ident, parent, password)\u001b[0m\n\u001b[1;32m   1217\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1218\u001b[0m                 \u001b[0;31m# re-raise KeyboardInterrupt, to truncate traceback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1219\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Interrupted by user\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1220\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1221\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlog\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwarning\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Invalid Message:\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexc_info\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mKeyboardInterrupt\u001b[0m: Interrupted by user"
          ]
        }
      ],
      "source": [
        "class Funcionario:\n",
        "  def __init__(self, nome, CPF, salario, departamento):\n",
        "    self.nome = nome\n",
        "    self.CPF = CPF\n",
        "    self.salario = salario\n",
        "    self.departamento = departamento\n",
        "\n",
        "  def bonificar(self):\n",
        "    self.salario *= 1.10\n",
        "\n",
        "\n",
        "class Gerente(Funcionario):\n",
        "  def __init__(self, nome, CPF, salario, departamento, senha, numFunc):\n",
        "    super().__init__(nome, CPF, salario, departamento)\n",
        "    self.senha = senha\n",
        "    self.numFunc = numFunc\n",
        "\n",
        "\n",
        "  def autenticar_senha(self, senha):\n",
        "    return self.senha == senha\n",
        "\n",
        "\n",
        "  def bonificar(self):\n",
        "    self.salario *= 1.15\n",
        "\n",
        "\n",
        "\n",
        "class Vendedor(Funcionario):\n",
        "  def __init__(self, nome, CPF, salario, departamento, quantVendas, comissao):\n",
        "    super().__init__(nome, CPF, salario, departamento)\n",
        "    self.quantVendas = quantVendas\n",
        "    self.comissao = comissao\n",
        "\n",
        "\n",
        "  def atualizaQuantidadeVendas(self, quantidade):\n",
        "    self.quantVendas += quantidade\n",
        "\n",
        "  def calculaSalario(self, comissao):\n",
        "    self.salario += self.comissao\n",
        "\n",
        "\n",
        "funcionarios = []\n",
        "gerentes = []\n",
        "vendedores = []\n",
        "\n",
        "\n",
        "while True:\n",
        "  print('\\n1 – Cadastrar funcionário')\n",
        "  print('2 – Cadastrar gerente')\n",
        "  print('3 – Cadastrar vendedor')\n",
        "  print('4 – Bonificar funcionário')\n",
        "  print('5 – Bonificar gerente')\n",
        "  print('6 – Autenticar senha gerente')\n",
        "  print('7 – Atualizar quantidade de vendas do vendedor')\n",
        "  print('8 – Calcular salário do vendedor')\n",
        "  print('9 - Listar funcionários')\n",
        "  print('10 - Listar gerentes')\n",
        "  print('11 - Listar vendedores')\n",
        "\n",
        "  while True:\n",
        "    try:\n",
        "      op = int(input('\\nSelecione uma opção válida: '))\n",
        "      if (op >= 1) and (op <= 11):\n",
        "        break\n",
        "      else:\n",
        "        print('\\nNúmero fora do intervalo. Tente novamente.')\n",
        "    except ValueError:\n",
        "      print('\\nOpção inválida. Digite novamente: ')\n",
        "  print(f'Opção {op} selecionada.')\n",
        "\n",
        "\n",
        "  if op == 1:\n",
        "    nome = input('\\nInsira o nome do funcionário: ')\n",
        "    CPF = input('Insira o CPF do funcionário: ')\n",
        "    salario = float(input('Insira o salário do funcionário: '))\n",
        "    departamento = input('Insira o departamento do funcionário: ')\n",
        "\n",
        "    f = Funcionario(nome, CPF, salario, departamento)\n",
        "    funcionarios.append(f)\n",
        "\n",
        "    print('\\nFuncionário cadastrado com sucesso!')\n",
        "\n",
        "\n",
        "  elif op == 2:\n",
        "    nome = input('\\nInsira o nome do gerente: ')\n",
        "    CPF = input('Insira o CPF do gerente: ')\n",
        "    salario = float(input('Insira o salário do gerente: '))\n",
        "    departamento = input('Insira o departamento do gerente: ')\n",
        "    senha = input('Insira a senha do gerente: ')\n",
        "    numFunc = int(input('Insira o número de funcionários gerenciados: '))\n",
        "\n",
        "    g = Gerente(nome, CPF, salario, departamento, senha, numFunc)\n",
        "    gerentes.append(g)\n",
        "\n",
        "    print('\\nGerente cadastrado com sucesso!')\n",
        "\n",
        "\n",
        "  elif op == 3:\n",
        "    nome = input('\\nInsira o nome do vendedor: ')\n",
        "    CPF = input('Insira o CPF do vendedor: ')\n",
        "    salario = float(input('Insira o salário do vendedor: '))\n",
        "    departamento = input('Insira o departamento do vendedor: ')\n",
        "    quantVendas = int(input('Insira o número de vendas: '))\n",
        "    comissao = float(input('Insira o valor da comissão: '))\n",
        "\n",
        "    v = Vendedor(nome, CPF, salario, departamento, quantVendas, comissao)\n",
        "    vendedores.append(v)\n",
        "\n",
        "    print('\\nVendedor cadastrado com sucesso!')\n",
        "\n",
        "  elif op == 4:\n",
        "    if len(funcionarios) == 0:\n",
        "      print('\\nNenhum funcionário cadastrado.')\n",
        "    else:\n",
        "      for f in funcionarios:\n",
        "        print('-', f.nome)\n",
        "\n",
        "      fun_nome = input('\\nDigite o nome do funcionário que deseja bonificar: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for f in funcionarios:\n",
        "        if f.nome.lower() == fun_nome.lower():\n",
        "          f.bonificar()\n",
        "          print(f'\\nSalário de {f.nome} atualizado: R${f.salario:.3f}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "  elif op == 5:\n",
        "    if len(gerentes) == 0:\n",
        "      print('\\nNenhum gerente cadastrado.')\n",
        "    else:\n",
        "      for g in gerentes:\n",
        "        print('-', g.nome)\n",
        "\n",
        "      ger_nome = input('\\nDigite o nome do gerente que deseja bonificar: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for g in gerentes:\n",
        "        if g.nome.lower() == ger_nome.lower():\n",
        "          g.bonificar()\n",
        "          print(f'\\nSalário de {g.nome} atualizado: R${g.salario:.2f}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "  elif op == 6:\n",
        "    if len(gerentes) == 0:\n",
        "      print('\\nNenhum gerente cadastrado.')\n",
        "    else:\n",
        "      for g in gerentes:\n",
        "        print('-', g.nome)\n",
        "\n",
        "      ger_nome = input('\\nDigite o nome do gerente: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for g in gerentes:\n",
        "        if g.nome.lower() == ger_nome.lower():\n",
        "          senha = input('Digite a senha: ')\n",
        "\n",
        "          if g.autenticar_senha(senha):\n",
        "            print('\\nSenha correta!')\n",
        "          else:\n",
        "            print('\\nSenha incorreta')\n",
        "\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "\n",
        "  elif op == 7:\n",
        "    if len(vendedores) == 0:\n",
        "      print('\\nNenhum vendedor cadastrado.')\n",
        "    else:\n",
        "      for v in vendedores:\n",
        "        print('-', v.nome)\n",
        "\n",
        "      ven_nome = input('\\nDigite o nome do vendedor: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for v in vendedores:\n",
        "        if v.nome.lower() == ven_nome.lower():\n",
        "          quantidade = int(input(f'Atualize a quantidade de vendas de {v.nome}: '))\n",
        "          v.atualizaQuantidadeVendas(quantidade)\n",
        "          print(f'Quantidade de vendas atualizada: {v.quantVendas}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "\n",
        "  elif op == 8:\n",
        "    if len(vendedores) == 0:\n",
        "      print('\\nNenhum vendedor cadastrado.')\n",
        "    else:\n",
        "      for v in vendedores:\n",
        "        print('-', v.nome)\n",
        "\n",
        "      ven_nome = input('\\nDigite o nome do vendedor: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for v in vendedores:\n",
        "        if v.nome.lower() == ven_nome.lower():\n",
        "          total = v.calculaSalario()\n",
        "\n",
        "          print(f'Salário + Comissão de {v.nome}: R${total:.2f}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "\n",
        "  elif op == 9:\n",
        "    if len(funcionarios) == 0:\n",
        "      print('\\nNenhum funcionário cadastrado.')\n",
        "    else:\n",
        "      for f in funcionarios:\n",
        "        print('-', f.nome)\n",
        "\n",
        "      fun_nome = input('Insira o nome do funcionário: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for f in funcionarios:\n",
        "        if f.nome.lower() == fun_nome.lower():\n",
        "          print(f'\\nNome: {f.nome} \\nCPF: {f.CPF} \\nSalário: R${f.salario:.2f} \\nDepartamento: {f.departamento}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado..')\n",
        "\n",
        "\n",
        "  elif op == 10:\n",
        "    if len(gerentes) == 0:\n",
        "      print('\\nNenhum gerente cadastrado.')\n",
        "    else:\n",
        "      for g in gerentes:\n",
        "        print('-', g.nome)\n",
        "\n",
        "      ger_nome = input('Insira o nome do gerente: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for g in gerentes:\n",
        "        if g.nome.lower() == ger_nome.lower():\n",
        "          print(f'\\nNome: {g.nome} \\nCPF: {g.CPF} \\nSalário: R${g.salario:.2f} \\nDepartamento: {g.departamento} \\nSenha: {g.senha} \\nN° Funcionários: {g.numFunc}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "\n",
        "  elif op == 11:\n",
        "    if len(vendedores) == 0:\n",
        "      print('\\nNenhum vendedor cadastrado.')\n",
        "    else:\n",
        "      for v in vendedores:\n",
        "        print('-', v.nome)\n",
        "\n",
        "      ven_nome = input('Insira o nome do vendedor: ')\n",
        "\n",
        "      encontrado = False\n",
        "\n",
        "      for v in vendedores:\n",
        "        if v.nome.lower() == ven_nome.lower():\n",
        "          print(f'\\nNome: {v.nome} \\nCPF: {v.CPF} \\nSalário: R${v.salario:.2f} \\nDepartamento: {v.departamento} \\nN° Vendas: {v.quantVendas} \\nComissão: {v.comissao}')\n",
        "          encontrado = True\n",
        "          break\n",
        "\n",
        "      if not encontrado:\n",
        "        print('\\nNome não encontrado.')\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ]
    }
  ]
}