{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bernardovigill/college_activities/blob/main/atividade_poo.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "background_save": true,
          "base_uri": "https://localhost:8080/"
        },
        "id": "cKwycSWjQs5n",
        "outputId": "d2d45c17-6b4f-44c1-d2e7-e2d4da06ec28"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "1 - Cadastrar montadora\n",
            "2 - Cadastrar modelo\n",
            "3 - Cadastrar carro\n",
            "4 - Listar montadoras\n",
            "5 - Listar modelos\n",
            "6 - Listar carros\n",
            "7 - Sair\n",
            "\n",
            "CADASTRAR MONTADORA\n"
          ]
        }
      ],
      "source": [
        "class Montadora:\n",
        "    def __init__(self, codMontadora, estado, razaoSocial):\n",
        "        self.codMontadora = codMontadora\n",
        "        self.estado = estado\n",
        "        self.razaoSocial = razaoSocial\n",
        "\n",
        "    def get_codMontadora(self):\n",
        "        return self.codMontadora\n",
        "\n",
        "    def get_estado(self):\n",
        "        return self.estado\n",
        "\n",
        "    def get_razaoSocial(self):\n",
        "        return self.razaoSocial\n",
        "\n",
        "    def set_codMontadora(self, codMontadora):\n",
        "        self.codMontadora = codMontadora\n",
        "\n",
        "    def set_estado(self, estado):\n",
        "        self.estado = estado\n",
        "\n",
        "    def set_razaoSocial(self, razaoSocial):\n",
        "        self.razaoSocial = razaoSocial\n",
        "\n",
        "\n",
        "class Modelo:\n",
        "    def __init__(self, codModelo, nomeModelo, montadora):\n",
        "        self.codModelo = codModelo\n",
        "        self.nomeModelo = nomeModelo\n",
        "        self.montadora = montadora\n",
        "\n",
        "    def get_codModelo(self):\n",
        "        return self.codModelo\n",
        "\n",
        "    def get_nomeModelo(self):\n",
        "        return self.nomeModelo\n",
        "\n",
        "    def get_montadora(self):\n",
        "        return self.montadora\n",
        "\n",
        "    def set_codModelo(self, codModelo):\n",
        "        self.codModelo = codModelo\n",
        "\n",
        "    def set_nomeModelo(self, nomeModelo):\n",
        "        self.nomeModelo = nomeModelo\n",
        "\n",
        "    def set_montadora(self, montadora):\n",
        "        self.montadora = montadora\n",
        "\n",
        "\n",
        "class Carro:\n",
        "    def __init__(self, placa, modelo, anoFab):\n",
        "        self.placa = placa\n",
        "        self.modelo = modelo\n",
        "        self.anoFab = anoFab\n",
        "\n",
        "    def get_placa(self):\n",
        "        return self.placa\n",
        "\n",
        "    def get_modelo(self):\n",
        "        return self.modelo\n",
        "\n",
        "    def get_anoFab(self):\n",
        "        return self.anoFab\n",
        "\n",
        "    def set_placa(self, placa):\n",
        "        self.placa = placa\n",
        "\n",
        "    def set_modelo(self, modelo):\n",
        "        self.modelo = modelo\n",
        "\n",
        "    def set_anoFab(self, anoFab):\n",
        "        self.anoFab = anoFab\n",
        "\n",
        "\n",
        "montadoras = []\n",
        "modelos = []\n",
        "carros = []\n",
        "\n",
        "while True:\n",
        "    print('\\n1 - Cadastrar montadora')\n",
        "    print('2 - Cadastrar modelo')\n",
        "    print('3 - Cadastrar carro')\n",
        "    print('4 - Listar montadoras')\n",
        "    print('5 - Listar modelos')\n",
        "    print('6 - Listar carros')\n",
        "    print('7 - Sair')\n",
        "\n",
        "    op = int(input('\\nSelecione uma opção: '))\n",
        "\n",
        "    if op == 1:\n",
        "        cod = int(input('Código da montadora: '))\n",
        "        estado = input('Estado: ')[:2]\n",
        "        razao = input('Razão social: ')\n",
        "\n",
        "        montadoras.append(Montadora(cod, estado, razao))\n",
        "        print('Montadora cadastrada!')\n",
        "\n",
        "    elif op == 2:\n",
        "        if not montadoras:\n",
        "            print('Cadastre uma montadora primeiro!')\n",
        "            continue\n",
        "\n",
        "        cod = int(input('Código do modelo: '))\n",
        "        nome = input('Nome do modelo: ')\n",
        "\n",
        "        for m in montadoras:\n",
        "            print(f'{m.get_codMontadora()} - {m.get_razaoSocial()}')\n",
        "\n",
        "        codSelect = int(input('Escolha o código da montadora: '))\n",
        "\n",
        "        montadora_escolhida = None\n",
        "        for m in montadoras:\n",
        "            if m.get_codMontadora() == codSelect:\n",
        "                montadora_escolhida = m\n",
        "                break\n",
        "\n",
        "        if montadora_escolhida:\n",
        "            modelos.append(Modelo(cod, nome, montadora_escolhida))\n",
        "            print('Modelo cadastrado!')\n",
        "        else:\n",
        "            print('Montadora não encontrada!')\n",
        "\n",
        "    elif op == 3:\n",
        "        if not modelos:\n",
        "            print('Cadastre um modelo primeiro!')\n",
        "            continue\n",
        "\n",
        "        placa = input('Placa: ')\n",
        "        ano = int(input('Ano: '))\n",
        "\n",
        "        for m in modelos:\n",
        "            print(f'{m.get_codModelo()} - {m.get_nomeModelo()}')\n",
        "\n",
        "        codSelect = int(input('Escolha o código do modelo: '))\n",
        "\n",
        "        modelo_escolhido = None\n",
        "        for m in modelos:\n",
        "            if m.get_codModelo() == codSelect:\n",
        "                modelo_escolhido = m\n",
        "                break\n",
        "\n",
        "        if modelo_escolhido:\n",
        "            carros.append(Carro(placa, modelo_escolhido, ano))\n",
        "            print('Carro cadastrado!')\n",
        "        else:\n",
        "            print('Modelo não encontrado!')\n",
        "\n",
        "    elif op == 4:\n",
        "        print('\\nMONTADORAS:')\n",
        "        for m in montadoras:\n",
        "            print(f'{m.get_codMontadora()} | {m.get_estado()} | {m.get_razaoSocial()}')\n",
        "\n",
        "    elif op == 5:\n",
        "        print('\\nMODELOS:')\n",
        "        for m in modelos:\n",
        "            print(f'{m.get_codModelo()} | {m.get_nomeModelo()} | {m.get_montadora().get_razaoSocial()}')\n",
        "\n",
        "    elif op == 6:\n",
        "        print('\\nCARROS:')\n",
        "        for c in carros:\n",
        "            print(f'{c.get_placa()} | {c.get_modelo().get_nomeModelo()} | {c.get_anoFab()}')\n",
        "\n",
        "    elif op == 7:\n",
        "        print('Saindo...')\n",
        "        break"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMVleNsXTVlPAokUkauE2W0",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}