{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bernardovigill/college_activities/blob/main/LivrariaOnline_POO.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qKAMPZ0wfJ0R",
        "outputId": "ef1fa562-e91e-4f87-cca1-944f1814ddef"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "-----------------------------\n",
            "====== LIVRARIA ONLINE ======\n",
            "1 - Cadastrar editora\n",
            "2 - Cadastar livro\n",
            "3 - Pesquisar editora\n",
            "4 - Pesquisar livro\n",
            "5 - Sair\n",
            "=============================\n",
            "-----------------------------\n"
          ]
        }
      ],
      "source": [
        "class Editora:\n",
        "    def __init__(self, codigo, razao_social, nome_contato, telefone):\n",
        "        self.codigo = codigo\n",
        "        self.razao_social = razao_social\n",
        "        self.nome_contato = nome_contato\n",
        "        self.telefone = telefone\n",
        "\n",
        "    def get_codigo(self):\n",
        "        return self.codigo\n",
        "\n",
        "    def get_razao_social(self):\n",
        "        return self.razao_social\n",
        "\n",
        "    def get_nome_contato(self):\n",
        "        return self.nome_contato\n",
        "\n",
        "    def get_telefone(self):\n",
        "        return self.telefone\n",
        "\n",
        "\n",
        "    def set_codigo(self, codigo):\n",
        "        self.codigo = codigo\n",
        "\n",
        "    def set_razao_social(self, razao_social):\n",
        "        self.razao_social = razao_social\n",
        "\n",
        "    def set_nome_contato(self, nome_contato):\n",
        "        self.nome_contato = nome_contato\n",
        "\n",
        "    def set_telefone(self, telefone):\n",
        "        self.telefone = telefone\n",
        "\n",
        "    def __str__(self):\n",
        "        return f\"Código: {self.codigo} | Razão Social: {self.razao_social} | Contato: {self.nome_contato} | Telefone: {self.telefone}\"\n",
        "\n",
        "\n",
        "class Livro:\n",
        "    def __init__(self, codigo, titulo, isbn, editora):\n",
        "        self.codigo = codigo\n",
        "        self.titulo = titulo\n",
        "        self.isbn = isbn\n",
        "        self.editora = editora\n",
        "\n",
        "\n",
        "    def get_codigo(self):\n",
        "        return self.codigo\n",
        "\n",
        "    def get_titulo(self):\n",
        "        return self.titulo\n",
        "\n",
        "    def get_isbn(self):\n",
        "        return self.isbn\n",
        "\n",
        "    def get_editora(self):\n",
        "        return self.editora\n",
        "\n",
        "\n",
        "    def set_codigo(self, codigo):\n",
        "        self.codigo = codigo\n",
        "\n",
        "    def set_titulo(self, titulo):\n",
        "        self.titulo = titulo\n",
        "\n",
        "    def set_isbn(self, isbn):\n",
        "        self.isbn = isbn\n",
        "\n",
        "    def set_editora(self, editora):\n",
        "        self.editora = editora\n",
        "\n",
        "    def __str__(self):\n",
        "        return (f\"Código: {self.codigo} | Título: {self.titulo} | ISBN: {self.isbn}\\n\"\n",
        "                f\"Editora: {self.editora.get_razao_social()} (Código: {self.editora.get_codigo()})\")\n",
        "\n",
        "\n",
        "\n",
        "editoras = []\n",
        "livros = []\n",
        "\n",
        "while True:\n",
        "  print('-----------------------------')\n",
        "  print('====== LIVRARIA ONLINE ======')\n",
        "  print('1 - Cadastrar editora')\n",
        "  print('2 - Cadastar livro')\n",
        "  print('3 - Pesquisar editora')\n",
        "  print('4 - Pesquisar livro')\n",
        "  print('5 - Sair')\n",
        "  print('=============================')\n",
        "  print('-----------------------------')\n",
        "\n",
        "  op = int(input('Selecione uma opção: '))\n",
        "\n",
        "  if op == 1:\n",
        "    print('\\n---- CADASTRO DE EDITORA ----')\n",
        "    codigo = int(input('Insira o código: '))\n",
        "    razaoSocial = input('Insira a razão social: ')\n",
        "    nomeContato = input('Insira o nome do contato: ')\n",
        "    while True:\n",
        "      telefone = input('Insira o número de telefone: ')\n",
        "      apenasNumeros = \"\".join(filter(str.isdigit, telefone))\n",
        "\n",
        "      if len(apenasNumeros) in [10, 11]:\n",
        "       print(f'Número {apenasNumeros} validado com sucesso!')\n",
        "       break\n",
        "      else:\n",
        "       print('Erro: o número deve conter 10 ou 11 dígitos numéricos. Tente novamente!')\n",
        "\n",
        "    ed = Editora(codigo, razaoSocial, nomeContato, telefone)\n",
        "    editoras.append(ed)\n",
        "    print('\\nCADASTRO REALIZADO!')\n",
        "\n",
        "\n",
        "  elif op == 2:\n",
        "    print('\\n------ CADASTRO DE LIVRO ------')\n",
        "    codigo = int(input('Insira o código: '))\n",
        "    titulo = input('Insira o título: ')\n",
        "    isbn = input('Insira o código ISBN: ')\n",
        "\n",
        "    for e in editoras:\n",
        "      print(f'\\nCódigo: {e.get_codigo()} \\nRazão Social: {e.get_razao_social()}')\n",
        "\n",
        "    numSelect = int(input('Selecione a editora para cadastrar o livro: '))\n",
        "\n",
        "    for e in editoras:\n",
        "      if numSelect == e.get_codigo():\n",
        "        nova = e\n",
        "        break\n",
        "    lv = Livro(codigo, titulo, isbn, e)\n",
        "    livros.append(lv)\n",
        "    print('\\nCADASTRO REALIZADO!')\n",
        "\n",
        "\n",
        "  elif op == 3:\n",
        "    print('\\n==== PESQUISAR EDITORA ====')\n",
        "    for e in editoras:\n",
        "      print(f'\\nCódigo: {e.get_codigo()} \\nRazão Social: {e.get_razao_social()} ')\n",
        "\n",
        "    for e in editoras:\n",
        "      if numSelect == e.get_codigo():\n",
        "        print(f'\\nNome Contato: {e.get_nome_contato()}, \\nN° Contato: {e.get_telefone()} ')\n",
        "        break\n",
        "\n",
        "\n",
        "  elif op == 4:\n",
        "    print('\\n==== PESQUISAR LIVRO ====')\n",
        "    for lv in livros:\n",
        "      print(f'\\nCódigo: ({lv.get_codigo()}) - Título: \"{lv.get_titulo()}\"')\n",
        "    numSelect = int(input('\\nInsira o código do livro: '))\n",
        "\n",
        "    for lv in livros:\n",
        "      if numSelect == lv.get_codigo():\n",
        "        print(f'Código: ({lv.get_codigo()}), Título: \"{lv.get_titulo()}\", ISBN: ({lv.get_isbn()}), Editora: {lv.get_editora(editoras)}')\n",
        "        break\n",
        "\n",
        "\n",
        "  elif op == 5:\n",
        "    print('Saindo...')\n",
        "    break\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "oKtkzAaLUj7N"
      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNAGJSxOa51Y/9YXM8JA+KM",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}